name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # ---- FRONTEND ----
    - name: Build Frontend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest ./frontend

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest

    # ---- BACKEND ----
    - name: Build Backend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mindsync-backend:latest ./backend

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mindsync-backend:latest

    # ---- DEPLOY TO SERVER ----
    - name: Deploy to Droplet
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          docker pull ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest &&
          docker pull ${{ secrets.DOCKER_USERNAME }}/mindsync-backend:latest &&

          docker stop frontend || true &&
          docker rm frontend || true &&
          docker stop backend || true &&
          docker rm backend || true &&

          docker run -d --name frontend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest &&
          docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/mindsync-backend:latest
        "
