name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Frontend Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest .

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest

    - name: Deploy to Droplet
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          docker pull ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest 

          docker stop frontend || true &&
          docker rm frontend || true &&

          docker run -d --name frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/mindsync-frontend:latest
        "
